---
- name: Setup Minecraft Server
  hosts: minecraft
  become: true

  vars:
    mc_dir: /home/ec2-user/minecraft
    mc_jar_url: https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
    mc_jar_name: server.jar

  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present

    - name: Create Minecraft directory
      file:
        path: "{{ mc_dir }}"
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Download Minecraft server .jar
      get_url:
        url: "{{ mc_jar_url }}"
        dest: "{{ mc_dir }}/{{ mc_jar_name }}"
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Accept Minecraft EULA
      copy:
        dest: "{{ mc_dir }}/eula.txt"
        content: "eula=true\n"
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Copy systemd service
      copy:
        src: minecraft.service
        dest: /etc/systemd/system/minecraft.service
        mode: '0644'

    - name: Reload systemd
      command: systemctl daemon-reexec

    - name: Enable Minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
